# 5 questions to answer:
1. how many highest-grossing films won Oscar?
2. Which genre has earned the most Oscars?
3. Is there is relationship between revenues and actors
4. Is there is relationship between actors and Oscars
5. Is there is relationship between revenues and Oscars

In [1]:
# load libraries
import pandas as pd
import numpy as np

In [2]:
# setting the path for the csv files
path_blockbusters = "data/blockbusters.csv"
path_oscars = "data/the_oscar_award.csv"

# read the csv files
blockbusters = pd.read_csv(path_blockbusters)
oscars = pd.read_csv(path_oscars)

# Exploring the data

In [3]:
# getting an idea of how the blockbusters dataframe looks like
blockbusters.head(5)

,Main_Genre,Genre_2,Genre_3,imdb_rating,length,rank_in_year,rating,studio,title,worldwide_gross,year
0,Action,Adventure,Drama,7.4,135,1,PG-13,Walt Disney Pictures,Black Panther,"$700,059,566",2018
1,Action,Adventure,Sci-Fi,8.5,156,2,PG-13,Walt Disney Pictures,Avengers: Infinity War,"$678,815,482",2018
2,Animation,Action,Adventure,7.8,118,3,PG,Pixar,Incredibles 2,"$608,581,744",2018
3,Action,Adventure,Drama,6.2,129,4,PG-13,Universal Pictures,Jurassic World: Fallen Kingdom,"$416,769,345",2018
4,Action,Comedy,NaN,7.8,119,5,R,20th Century Fox,Deadpool 2,"$318,491,426",2018

In [4]:
# getting an idea of how the oscars dataframe looks like
oscars.head(5)

,year_film,year_ceremony,ceremony,category,name,film,winner
0,1927,1928,1,ACTOR,Richard Barthelmess,The Noose,False
1,1927,1928,1,ACTOR,Emil Jannings,The Last Command,True
2,1927,1928,1,ACTRESS,Louise Dresser,A Ship Comes In,False
3,1927,1928,1,ACTRESS,Janet Gaynor,7th Heaven,True
4,1927,1928,1,ACTRESS,Gloria Swanson,Sadie Thompson,False

# Analysing the dataframes

## Differences
The data from the oscars starts from 1927.
The data from the blockbusters starts at 1975.
If we combine the data it makes sense to limit the oscar data to data >= 1975.

## Similarities
The dataframes have two columns in common:
1. The title of the film (title/film)
2. The year the film was produced (year/year_film)

In [5]:
# limit the oscar data to the year 1975 and up
oscars_1975 = oscars.loc[oscars["year_film"] >= 1975]

# Merging the data
We can merge the data on title and the year of the movie. To do this, we want to rename the columns so that they hold the same name

In [6]:
# Rename the column "title" to "film" in oscars_1975 and check that it worked
oscars_1975 = oscars_1975.rename(columns={"film": "title"})
oscars_1975.head(2)

,year_film,year_ceremony,ceremony,category,name,title,winner
5298,1975,1976,48,ACTOR,Walter Matthau,The Sunshine Boys,False
5299,1975,1976,48,ACTOR,Jack Nicholson,One Flew over the Cuckoo's Nest,True

In [7]:
# Rename the column "year" to "film" in blockbusters and check that it worked
blockbusters = blockbusters.rename(columns={"year": "year_film"})
blockbusters.head(2)

,Main_Genre,Genre_2,Genre_3,imdb_rating,length,rank_in_year,rating,studio,title,worldwide_gross,year_film
0,Action,Adventure,Drama,7.4,135,1,PG-13,Walt Disney Pictures,Black Panther,"$700,059,566",2018
1,Action,Adventure,Sci-Fi,8.5,156,2,PG-13,Walt Disney Pictures,Avengers: Infinity War,"$678,815,482",2018

In [8]:
# Merge the files and check that it worked
oscars_and_busters = oscars_1975.merge(blockbusters, on = ['title', 'year_film'])
oscars_and_busters.head(2)

,year_film,year_ceremony,ceremony,category,name,title,winner,Main_Genre,Genre_2,Genre_3,imdb_rating,length,rank_in_year,rating,studio,worldwide_gross
0,1975,1976,48,ACTOR,Al Pacino,Dog Day Afternoon,False,Drama,Crime,NaN,8.1,125,4,R,Warner Bros,"$50,000,000.00"
1,1975,1976,48,ACTOR IN A SUPPORTING ROLE,Chris Sarandon,Dog Day Afternoon,False,Drama,Crime,NaN,8.1,125,4,R,Warner Bros,"$50,000,000.00"

In [9]:
# check NaN 
oscars_and_busters.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 843 entries, 0 to 842
Data columns (total 16 columns):
year_film          843 non-null int64
year_ceremony      843 non-null int64
ceremony           843 non-null int64
category           843 non-null object
name               843 non-null object
title              843 non-null object
winner             843 non-null bool
Main_Genre         843 non-null object
Genre_2            775 non-null object
Genre_3            505 non-null object
imdb_rating        843 non-null float64
length             843 non-null int64
rank_in_year       843 non-null int64
rating             843 non-null object
studio             843 non-null object
worldwide_gross    843 non-null object
dtypes: bool(1), float64(1), int64(5), object(9)
memory usage: 106.2+ KB

In [10]:
df = oscars_and_busters

In [11]:
# how many highest-grossing films won Oscar?
df1 = df.loc[df["winner"] == True]

In [12]:
df1.sort_values('worldwide_gross')

,year_film,year_ceremony,ceremony,category,name,title,winner,Main_Genre,Genre_2,Genre_3,imdb_rating,length,rank_in_year,rating,studio,worldwide_gross
753,2010,2011,83,COSTUME DESIGN,Colleen Atwood,Alice in Wonderland,True,Fantasy,Family,Adventure,6.5,108,2,PG,Walt Disney Pictures,"$1,025,467,110.00"
752,2010,2011,83,ART DIRECTION,Production Design: Robert Stromberg; Set Decor...,Alice in Wonderland,True,Fantasy,Family,Adventure,6.5,108,2,PG,Walt Disney Pictures,"$1,025,467,110.00"
748,2010,2011,83,MUSIC (Original Song),Music and Lyric by Randy Newman,Toy Story 3,True,Comedy,Animation,Adventure,8.4,103,1,G,Walt Disney Pictures,"$1,063,171,911.00"
747,2010,2011,83,ANIMATED FEATURE FILM,Lee Unkrich,Toy Story 3,True,Comedy,Animation,Adventure,8.4,103,1,G,Walt Disney Pictures,"$1,063,171,911.00"
698,2006,2007,79,VISUAL EFFECTS,"John Knoll, Hal Hickel, Charles Gibson and All...",Pirates of the Caribbean: Dead Man's Chest,True,Fantasy,Adventure,Action,7.3,151,1,PG-13,Walt Disney Pictures,"$1,066,179,725.00"
771,2012,2013,85,MUSIC (Original Song),Music and Lyric by Adele Adkins and Paul Epworth,Skyfall,True,Thriller,Adventure,Action,7.8,143,2,PG-13,Metro-Goldwyn-Mayer,"$1,108,561,013.00"
772,2012,2013,85,SOUND EDITING,Per Hallberg and Karen Baker Landers,Skyfall,True,Thriller,Adventure,Action,7.8,143,2,PG-13,Metro-Goldwyn-Mayer,"$1,108,561,013.00"
654,2003,2004,76,DIRECTING,Peter Jackson,The Lord of the Rings: The Return of the King,True,Fantasy,Adventure,Western,8.9,201,1,PG-13,Warner Bros,"$1,119,929,521.00"
657,2003,2004,76,MUSIC (Original Score),Howard Shore,The Lord of the Rings: The Return of the King,True,Fantasy,Adventure,Western,8.9,201,1,PG-13,Warner Bros,"$1,119,929,521.00"
652,2003,2004,76,ART DIRECTION,Art Direction: Grant Major; Set Decoration: Da...,The Lord of the Rings: The Return of the King,True,Fantasy,Adventure,Western,8.9,201,1,PG-13,Warner Bros,"$1,119,929,521.00"
662,2003,2004,76,WRITING (Adapted Screenplay),"Screenplay by Fran Walsh, Philippa Boyens & Pe...",The Lord of the Rings: The Return of the King,True,Fantasy,Adventure,Western,8.9,201,1,PG-13,Warner Bros,"$1,119,929,521.00"
661,2003,2004,76,VISUAL EFFECTS,"Jim Rygiel, Joe Letteri, Randall William Cook ...",The Lord of the Rings: The Return of the King,True,Fantasy,Adventure,Western,8.9,201,1,PG-13,Warner Bros,"$1,119,929,521.00"
660,2003,2004,76,SOUND MIXING,"Christopher Boyes, Michael Semanick, Michael H...",The Lord of the Rings: The Return of the King,True,Fantasy,Adventure,Western,8.9,201,1,PG-13,Warner Bros,"$1,119,929,521.00"
659,2003,2004,76,BEST PICTURE,"Barrie M. Osborne, Peter Jackson and Fran Wals...",The Lord of the Rings: The Return of the King,True,Fantasy,Adventure,Western,8.9,201,1,PG-13,Warner Bros,"$1,119,929,521.00"
658,2003,2004,76,MUSIC (Original Song),Music and Lyric by Fran Walsh and Howard Shore...,The Lord of the Rings: The Return of the King,True,Fantasy,Adventure,Western,8.9,201,1,PG-13,Warner Bros,"$1,119,929,521.00"
655,2003,2004,76,FILM EDITING,Jamie Selkirk,The Lord of the Rings: The Return of the King,True,Fantasy,Adventure,Western,8.9,201,1,PG-13,Warner Bros,"$1,119,929,521.00"
653,2003,2004,76,COSTUME DESIGN,Ngila Dickson and Richard Taylor,The Lord of the Rings: The Return of the King,True,Fantasy,Adventure,Western,8.9,201,1,PG-13,Warner Bros,"$1,119,929,521.00"
656,2003,2004,76,MAKEUP,Richard Taylor and Peter King,The Lord of the Rings: The Return of the King,True,Fantasy,Adventure,Western,8.9,201,1,PG-13,Warner Bros,"$1,119,929,521.00"
790,2013,2014,86,MUSIC (Original Song),Music and Lyric by Kristen Anderson-Lopez and ...,Frozen,True,Comedy,Animation,Adventure,7.7,102,1,PG,Walt Disney Pictures,"$1,274,219,009.00"
789,2013,2014,86,ANIMATED FEATURE FILM,"Chris Buck, Jennifer Lee and Peter Del Vecho",Frozen,True,Comedy,Animation,Adventure,7.7,102,1,PG,Walt Disney Pictures,"$1,274,219,009.00"
509,1997,1998,70,DIRECTING,James Cameron,Titanic,True,Romance,Drama,NaN,7.7,194,1,PG-13,Paramount Pictures,"$1,843,201,268.00"
517,1997,1998,70,VISUAL EFFECTS,"Robert Legato, Mark Lasoff, Thomas L. Fisher, ...",Titanic,True,Romance,Drama,NaN,7.7,194,1,PG-13,Paramount Pictures,"$1,843,201,268.00"
516,1997,1998,70,SOUND EFFECTS EDITING,"Tom Bellfort, Christopher Boyes",Titanic,True,Romance,Drama,NaN,7.7,194,1,PG-13,Paramount Pictures,"$1,843,201,268.00"
510,1997,1998,70,FILM EDITING,"Conrad Buff, James Cameron, Richard A. Harris",Titanic,True,Romance,Drama,NaN,7.7,194,1,PG-13,Paramount Pictures,"$1,843,201,268.00"
515,1997,1998,70,SOUND,"Gary Rydstrom, Tom Johnson, Gary Summers, Mark...",Titanic,True,Romance,Drama,NaN,7.7,194,1,PG-13,Paramount Pictures,"$1,843,201,268.00"
513,1997,1998,70,MUSIC (Original Song),Music by James Horner; Lyric by Will Jennings,Titanic,True,Romance,Drama,NaN,7.7,194,1,PG-13,Paramount Pictures,"$1,843,201,268.00"
512,1997,1998,70,MUSIC (Original Dramatic Score),James Horner,Titanic,True,Romance,Drama,NaN,7.7,194,1,PG-13,Paramount Pictures,"$1,843,201,268.00"
514,1997,1998,70,BEST PICTURE,"James Cameron and Jon Landau, Producers",Titanic,True,Romance,Drama,NaN,7.7,194,1,PG-13,Paramount Pictures,"$1,843,201,268.00"
508,1997,1998,70,COSTUME DESIGN,Deborah L. Scott,Titanic,True,Romance,Drama,NaN,7.7,194,1,PG-13,Paramount Pictures,"$1,843,201,268.00"
507,1997,1998,70,CINEMATOGRAPHY,Russell Carpenter,Titanic,True,Romance,Drama,NaN,7.7,194,1,PG-13,Paramount Pictures,"$1,843,201,268.00"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279,1987,1988,60,ACTRESS IN A SUPPORTING ROLE,Olympia Dukakis,Moonstruck,True,Romance,Drama,Comedy,7.1,102,5,PG,Metro-Goldwyn-Mayer,"$80,640,528.00"
278,1987,1988,60,ACTRESS IN A LEADING ROLE,Cher,Moonstruck,True,Romance,Drama,Comedy,7.1,102,5,PG,Metro-Goldwyn-Mayer,"$80,640,528.00"
122,1979,1980,52,VISUAL EFFECTS,"H.R. Giger, Carlo Rambaldi, Brian Johnson, Nic...",Alien,True,Sci-Fi,Horror,NaN,8.5,117,6,R,20th Century Fox,"$80,931,801.00"
83,1978,1979,51,ART DIRECTION,"Art Direction: Paul Sylbert, Edwin O'Donovan;...",Heaven Can Wait,True,Sport,Romance,Comedy,6.9,101,5,PG,Paramount Pictures,"$81,640,278.00"
492,1996,1997,69,VISUAL EFFECTS,"Volker Engel, Douglas Smith, Clay Pinney, Jose...",Independence Day,True,Sci-Fi,Adventure,Action,6.9,145,1,PG-13,20th Century Fox,"$817,400,891.00"
756,2010,2011,83,CINEMATOGRAPHY,Wally Pfister,Inception,True,Sci-Fi,Mystery,Action,8.8,148,4,PG-13,Warner Bros,"$825,531,030.00"
759,2010,2011,83,SOUND EDITING,Richard King,Inception,True,Sci-Fi,Mystery,Action,8.8,148,4,PG-13,Warner Bros,"$825,531,030.00"
760,2010,2011,83,SOUND MIXING,"Lora Hirschberg, Gary A. Rizzo and Ed Novick",Inception,True,Sci-Fi,Mystery,Action,8.8,148,4,PG-13,Warner Bros,"$825,531,030.00"
761,2010,2011,83,VISUAL EFFECTS,"Paul Franklin, Chris Corbould, Andrew Lockley ...",Inception,True,Sci-Fi,Mystery,Action,8.8,148,4,PG-13,Warner Bros,"$825,531,030.00"
119,1979,1980,52,SOUND,"Walter Murch, Mark Berger, Richard Beggs, Nat ...",Apocalypse Now,True,War,Drama,NaN,8.5,153,4,R,Metro-Goldwyn-Mayer,"$83,471,511.00"
115,1979,1980,52,CINEMATOGRAPHY,Vittorio Storaro,Apocalypse Now,True,War,Drama,NaN,8.5,153,4,R,Metro-Goldwyn-Mayer,"$83,471,511.00"
230,1985,1986,58,ACTOR IN A SUPPORTING ROLE,Don Ameche,Cocoon,True,Sci-Fi,NaN,NaN,6.6,117,6,PG-13,20th Century Fox,"$85,313,124.00"
231,1985,1986,58,VISUAL EFFECTS,"Ken Ralston, Ralph McQuarrie, Scott Farrar, Da...",Cocoon,True,Sci-Fi,NaN,NaN,6.6,117,6,PG-13,20th Century Fox,"$85,313,124.00"
262,1986,1987,59,VISUAL EFFECTS,"Robert Skotak, Stan Winston, John Richardson, ...",Aliens,True,Sci-Fi,Adventure,Action,8.4,137,7,R,20th Century Fox,"$86,160,248.00"
261,1986,1987,59,SOUND EFFECTS EDITING,Don Sharpe,Aliens,True,Sci-Fi,Adventure,Action,8.4,137,7,R,20th Century Fox,"$86,160,248.00"
648,2003,2004,76,ANIMATED FEATURE FILM,Andrew Stanton,Finding Nemo,True,Comedy,Animation,Adventure,8.2,100,2,G,Pixar,"$867,893,978.00"
613,2001,2002,74,VISUAL EFFECTS,"Jim Rygiel, Randall William Cook, Richard Tayl...",The Lord of the Rings: The Fellowship of the Ring,True,Fantasy,Adventure,NaN,8.8,178,2,PG-13,Warner Bros,"$870,761,744.00"
609,2001,2002,74,MUSIC (Original Score),Howard Shore,The Lord of the Rings: The Fellowship of the Ring,True,Fantasy,Adventure,NaN,8.8,178,2,PG-13,Warner Bros,"$870,761,744.00"
608,2001,2002,74,MAKEUP,"Peter Owen, Richard Taylor",The Lord of the Rings: The Fellowship of the Ring,True,Fantasy,Adventure,NaN,8.8,178,2,PG-13,Warner Bros,"$870,761,744.00"
604,2001,2002,74,CINEMATOGRAPHY,Andrew Lesnie,The Lord of the Rings: The Fellowship of the Ring,True,Fantasy,Adventure,NaN,8.8,178,2,PG-13,Warner Bros,"$870,761,744.00"
436,1993,1994,66,SOUND,"Gary Summers, Gary Rydstrom, Shawn Murphy, Ron...",Jurassic Park,True,Thriller,Sci-Fi,Adventure,8.0,127,1,PG-13,Universal Pictures,"$914,691,118.00"
437,1993,1994,66,SOUND EFFECTS EDITING,"Gary Rydstrom, Richard Hymns",Jurassic Park,True,Thriller,Sci-Fi,Adventure,8.0,127,1,PG-13,Universal Pictures,"$914,691,118.00"
438,1993,1994,66,VISUAL EFFECTS,"Dennis Muren, Stan Winston, Phil Tippett, Mich...",Jurassic Park,True,Thriller,Sci-Fi,Adventure,8.0,127,1,PG-13,Universal Pictures,"$914,691,118.00"
207,1983,1984,56,MUSIC (Original Song),Music by Giorgio Moroder; Lyric by Keith Forse...,Flashdance,True,Romance,Music,Drama,6.1,95,3,R,Paramount Pictures,"$92,921,203.00"
634,2002,2003,75,VISUAL EFFECTS,"Jim Rygiel, Joe Letteri, Randall William Cook,...",The Lord of the Rings: The Two Towers,True,Fantasy,Adventure,NaN,8.7,179,1,PG-13,Warner Bros,"$926,287,400.00"
633,2002,2003,75,SOUND EDITING,"Ethan Van der Ryn, Michael Hopkins",The Lord of the Rings: The Two Towers,True,Fantasy,Adventure,NaN,8.7,179,1,PG-13,Warner Bros,"$926,287,400.00"
151,1981,1982,54,ACTOR IN A SUPPORTING ROLE,John Gielgud,Arthur,True,Romance,Comedy,NaN,6.9,97,4,PG,Warner Bros,"$95,461,682.00"
152,1981,1982,54,MUSIC (Original Song),"Music and Lyric by Burt Bacharach, Carole Baye...",Arthur,True,Romance,Comedy,NaN,6.9,97,4,PG,Warner Bros,"$95,461,682.00"
715,2008,2009,81,SOUND EDITING,Richard King,The Dark Knight,True,Drama,Crime,Action,9.0,152,1,PG-13,Warner Bros,"$997,000,000.00"
710,2008,2009,81,ACTOR IN A SUPPORTING ROLE,Heath Ledger,The Dark Knight,True,Drama,Crime,Action,9.0,152,1,PG-13,Warner Bros,"$997,000,000.00"

In [13]:
# top 3 movies - Alice in Wonderland, Toy Story 3, Pirates of the Caribbean

In [21]:
# 2. Which genre has earned the most Oscars?
genre = df1.groupby(['title'], sort=False, as_index=False)['Main_Genre'].first()

In [22]:
genre.head()

                     title Main_Genre
0        Dog Day Afternoon      Drama
1                  Shampoo    Romance
2                    Rocky      Sport
3  All the President's Men   Thriller
4                King Kong     Horror

In [23]:
genre['Main_Genre'].value_counts()

Romance      21
Sci-Fi       12
Drama        12
Fantasy      10
Thriller      9
Comedy        9
Animation     7
Action        5
War           5
Adventure     4
Sport         3
Music         2
History       2
Crime         2
Family        1
Horror        1
Name: Main_Genre, dtype: int64

In [43]:
# 3. Which studio has the best Oscars to total movies produced ratio?
# find number of movies won by studio, total movies, and merge on studio. Divide movies won by total movies
winners = df1.groupby(['title'], sort=False, as_index=False)['studio'].first()

In [50]:
winners['studio'].value_counts()

Warner Bros             19
Walt Disney Pictures    16
Paramount Pictures      15
Universal Pictures      11
20th Century Fox         9
Metro-Goldwyn-Mayer      9
Columbia Pictures        8
Pixar                    7
Sony Pictures            6
DreamWorks               4
Lionsgate Films          1
Name: studio, dtype: int64

In [76]:
# convert to dataframe
winners1 = winners['studio'].value_counts().rename_axis('studio').reset_index(name='oscars')

In [77]:
winners1.head()

                 studio  oscars
0           Warner Bros      19
1  Walt Disney Pictures      16
2    Paramount Pictures      15
3    Universal Pictures      11
4      20th Century Fox       9

In [67]:
total = df.groupby(['title'], sort=False, as_index=False)['studio'].first()

In [69]:
total['studio'].value_counts()

Warner Bros             50
Walt Disney Pictures    40
Paramount Pictures      35
Universal Pictures      23
20th Century Fox        21
Columbia Pictures       18
Metro-Goldwyn-Mayer     17
Sony Pictures           12
Pixar                    9
DreamWorks               8
IFC Films                1
Newmarket Films          1
Lionsgate Films          1
Name: studio, dtype: int64

In [72]:
# convert to dataframe
total1 = total['studio'].value_counts().rename_axis('studio').reset_index(name='total_movies')

In [73]:
total1.head()

                 studio  total_movies
0           Warner Bros            50
1  Walt Disney Pictures            40
2    Paramount Pictures            35
3    Universal Pictures            23
4      20th Century Fox            21

In [78]:
merged = winners1.merge(total1, on = ['studio'])

In [79]:
merged.head()

                 studio  oscars  total_movies
0           Warner Bros      19            50
1  Walt Disney Pictures      16            40
2    Paramount Pictures      15            35
3    Universal Pictures      11            23
4      20th Century Fox       9            21

In [80]:
merged['ratio_oscars'] = merged['oscars']/merged['total_movies']

In [85]:
merged.sort_values('ratio_oscars', ascending=False)

                  studio  oscars  total_movies  ratio_oscars
10       Lionsgate Films       1             1      1.000000
7                  Pixar       7             9      0.777778
5    Metro-Goldwyn-Mayer       9            17      0.529412
8          Sony Pictures       6            12      0.500000
9             DreamWorks       4             8      0.500000
3     Universal Pictures      11            23      0.478261
6      Columbia Pictures       8            18      0.444444
2     Paramount Pictures      15            35      0.428571
4       20th Century Fox       9            21      0.428571
1   Walt Disney Pictures      16            40      0.400000
0            Warner Bros      19            50      0.380000

In [ ]:
# Although Warner Bros makes the largest total movies, it's oscar winning ratio is the lowest.
# Pixer has a favouritable ratio at 78%.